;;; phi-search-autoloads.el --- automatically extracted autoloads (do not edit)   -*- lexical-binding: t -*-
;; Generated by the `loaddefs-generate' function.

;; This file is part of GNU Emacs.

;;; Code:

(add-to-list 'load-path (or (and load-file-name (directory-file-name (file-name-directory load-file-name))) (car load-path)))



;;; Generated autoloads from phi-replace.el

(autoload 'phi-replace "phi-replace" "\
replace command using phi-search" t)
(autoload 'phi-replace-query "phi-replace" "\
replace command using phi-search" t)
(register-definition-prefixes "phi-replace" '("phi-replace-"))


;;; Generated autoloads from phi-search.el

(autoload 'phi-search "phi-search" "\
incremental search command compatible with \"multiple-cursors\"

(fn &optional USE-ISEARCH)" t)
(autoload 'phi-search-backward "phi-search" "\
incremental search command compatible with \"multiple-cursors\"

(fn &optional USE-ISEARCH)" t)
(register-definition-prefixes "phi-search" '("phi-search-"))


;;; Generated autoloads from phi-search-core.el

(register-definition-prefixes "phi-search-core" '("phi-search-"))

;;; End of scraped data

(provide 'phi-search-autoloads)

;; Local Variables:
;; version-control: never
;; no-byte-compile: t
;; no-update-autoloads: t
;; no-native-compile: t
;; coding: utf-8-emacs-unix
;; End:

;;; phi-search-autoloads.el ends here
