;;; mc-extras-autoloads.el --- automatically extracted autoloads (do not edit)   -*- lexical-binding: t -*-
;; Generated by the `loaddefs-generate' function.

;; This file is part of GNU Emacs.

;;; Code:

(add-to-list 'load-path (or (and load-file-name (directory-file-name (file-name-directory load-file-name))) (car load-path)))



;;; Generated autoloads from mc-cua.el

(autoload 'mc/cua-rectangle-to-multiple-cursors "mc-cua" "\
Turn CUA rectangle mode into multiple-cursors mode, keeping insert positions and selections." t)
(autoload 'mc/cua-rectangle-setup "mc-cua" "\
Enable interaction between multiple cursors and CUA rectangle copy & paste.")
(register-definition-prefixes "mc-cua" '("mc/cua-saved-kill-ring"))


;;; Generated autoloads from mc-freeze.el

(autoload 'mc/freeze-fake-cursors "mc-freeze" "\
Freeze fake cursors for later reactivation.

With ARG or when there is no fake cursor, create a fake cursor at
point before freezing fake cursors.

(fn &optional ARG)" t)
(autoload 'mc/unfreeze-fake-cursors "mc-freeze" "\
Unfreeze frozen fake cursors." t)
(autoload 'mc/freeze-fake-cursors-dwim "mc-freeze" "\
Freeze or unfreeze fake cursors depending on the current state.

With ARG, always create a fake cursor at point then freeze fake
cursors.

(fn &optional ARG)" t)
(register-definition-prefixes "mc-freeze" '("mc-freeze--"))


;;; Generated autoloads from mc-mark-extras.el

(autoload 'mc/mark-next-sexps "mc-mark-extras" "\
Mark next ARG sexps.

(fn ARG)" t)
(autoload 'mc/mark-previous-sexps "mc-mark-extras" "\
Mark previous ARG sexps.

(fn ARG)" t)
(autoload 'mc/mark-all-below "mc-mark-extras" "\
Mark lines below until the cursor hits a line shorter than the current column position." t)
(autoload 'mc/mark-all-above "mc-mark-extras" "\
Mark lines above until the cursor hits a line shorter than the current column position." t)
(register-definition-prefixes "mc-mark-extras" '("mc/mark-sexps"))


;;; Generated autoloads from mc-move.el

(autoload 'mc/move-to-column "mc-move" "\
Move every cursor to column COLUMN.

If COLUMN is omitted, move every fake cursor to the same column
as the real cursor.

(fn COLUMN)" t)
(autoload 'mc/compare-chars "mc-move" "\
Move all cursors forward while the characters at the cursors all match.

With an optional ARG, move backwards by calling `mc/compare-chars-backward'.
This command pushes the mark before moving cursors.

(fn &optional ARG)" t)
(autoload 'mc/compare-chars-forward "mc-move" "\
Move all cursors forward while the characters at the cursors all match.

This command pushes the mark before moving cursors." t)
(autoload 'mc/compare-chars-backward "mc-move" "\
Backwards version of `mc/compare-chars-forward'." t)


;;; Generated autoloads from mc-rect.el

(autoload 'mc/rect-rectangle-to-multiple-cursors "mc-rect" "\
Turn rectangle-mark-mode into multiple-cursors mode, keeping selections.

(fn START END)" t)


;;; Generated autoloads from mc-remove.el

(autoload 'mc/remove-current-cursor "mc-remove" "\
Remove the current cursor by replacing the next fake cursor." t)
(autoload 'mc/remove-duplicated-cursors "mc-remove" "\
Remove duplicated fake cursors, including ones that overlap the real cursor." t)
(autoload 'mc/remove-cursors-at-bol "mc-remove" "\
Remove cursors at BOL, either fake or real." t)
(autoload 'mc/remove-cursors-at-eol "mc-remove" "\
Remove cursors at EOL, either fake or real." t)
(autoload 'mc/remove-cursors-on-blank-lines "mc-remove" "\
Remove cursors on blank lines, either fake or real." t)

;;; End of scraped data

(provide 'mc-extras-autoloads)

;; Local Variables:
;; version-control: never
;; no-byte-compile: t
;; no-update-autoloads: t
;; no-native-compile: t
;; coding: utf-8-emacs-unix
;; End:

;;; mc-extras-autoloads.el ends here
